/**
 * Vantarius — Main Orchestrator
 *
 * Reads an Excel CRM enriched by AxioMariuS (or manually) and runs a
 * multi-stage LinkedIn outreach sequence:
 *
 *   J0  — Send connection request with personalized note
 *   J3  — Follow-up DM (proof / context)
 *   J7  — Second follow-up (added value)
 *   J10 — Closing message (clean exit)
 *
 * Messages are generated by a local LLM (Ollama) using the signal data
 * from the CRM and validated before sending.
 *
 * Usage:
 *   node src/main.js           — Run full pipeline
 *   node src/main.js --dry-run — Preview messages without sending
 *   node src/main.js --stage J0  — Process only J0 leads
 */

'use strict';

const { addExtra }       = require('puppeteer-extra');
const rebrowserPuppeteer = require('rebrowser-puppeteer');
const puppeteer          = addExtra(rebrowserPuppeteer);
const ExcelJS       = require('exceljs');
const path          = require('path');

const cfg           = require('./config_loader');
const logger        = require('./logger');
const { atomicWriteCRM, validateCRMIntegrity } = require('./crm_writer');
const { alreadyProcessedToday, markAsProcessed, getTodayCount } = require('./dedup_guard');
const { polishMessage } = require('./llm_polisher');
const { sendConnectionRequest, sendDirectMessage } = require('./linkedin_sender');

// ── CLI flags ─────────────────────────────────────────────────────────────────

const DRY_RUN    = process.argv.includes('--dry-run') || cfg.get('debug.dry_run', false);
const STAGE_ONLY = process.argv.find(a => a.startsWith('--stage'))?.split(' ')[1] ||
                   process.argv[process.argv.indexOf('--stage') + 1];

// ── CRM helpers ───────────────────────────────────────────────────────────────

const COLS = cfg.get('crm.columns');

function getCell(row, colKey) {
    const idx = COLS[colKey];
    if (!idx) return null;
    const cell = row.getCell(idx);
    if (cell.value?.text) return cell.value.text;
    return cell.value ?? null;
}

function setCell(row, colKey, value) {
    const idx = COLS[colKey];
    if (idx) row.getCell(idx).value = value;
}

function randomDelay(min, max) {
    const ms = Math.floor(Math.random() * (max - min + 1)) + min;
    logger.info(`Pause: ${(ms / 1000).toFixed(0)}s`);
    return new Promise(r => setTimeout(r, ms));
}

// ── Timing logic ──────────────────────────────────────────────────────────────

function daysSince(dateValue) {
    if (!dateValue) return null;
    const d = dateValue instanceof Date ? dateValue : new Date(dateValue);
    if (isNaN(d.getTime())) return null;
    return Math.floor((Date.now() - d.getTime()) / 86400000);
}

function isWorkingHours() {
    const h     = new Date().getHours();
    const start = cfg.get('working_hours.start', 9);
    const end   = cfg.get('working_hours.end', 18);
    return h >= start && h < end;
}

function getStage(stage, dateContact) {
    const s = String(stage || '').toLowerCase();

    // New lead — J0
    const j0Stages = ['new', 'lead', 'nouveau'];
    if (j0Stages.some(k => s.includes(k))) return 'J0';

    // Already sent — check timing for follow-ups
    const days = daysSince(dateContact);
    if (days === null) return null;

    const timing = cfg.get('timing', { j3: 3, j7: 7, j10: 10 });
    const statusJ3  = cfg.get('crm.status_j0', 'Invite sent');
    const statusJ7  = cfg.get('crm.status_j3', 'Follow-up J+3');

    if (s.includes('invite sent') || s.includes(statusJ3.toLowerCase())) {
        if (days >= timing.j7) return 'J7';
        if (days >= timing.j3) return 'J3';
        return null;
    }

    if (s.includes('follow-up j+3') || s.includes(statusJ7.toLowerCase())) {
        if (days >= timing.j10) return 'J10';
        if (days >= timing.j7) return 'J7';
        return null;
    }

    if (s.includes('follow-up j+7')) {
        if (days >= timing.j10) return 'J10';
        return null;
    }

    return null;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function run() {
    logger.startSession();

    if (DRY_RUN) logger.warn('DRY RUN — no messages will be sent.');

    const crmPath = path.resolve(process.cwd(), cfg.get('crm.file', 'CRM.xlsx'));

    if (!validateCRMIntegrity(crmPath)) {
        logger.error(`CRM not found or corrupted: ${crmPath}`);
        process.exit(1);
    }

    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.readFile(crmPath);
    const sheet     = workbook.getWorksheet(cfg.get('crm.sheet', 'Pipeline'));
    const startRow  = cfg.get('crm.data_start_row', 2);

    if (!sheet) {
        logger.error(`Sheet "${cfg.get('crm.sheet')}" not found.`);
        process.exit(1);
    }

    logger.info(`Sheet loaded: ${sheet.actualRowCount} rows`);

    // Check quotas
    const quotaDay  = cfg.get('linkedin.quota_per_day', 15);
    const todayDone = getTodayCount();
    logger.info(`Today's sent: ${todayDone} / ${quotaDay}`);
    if (todayDone >= quotaDay) {
        logger.warn(`Daily quota reached (${quotaDay}). Run again tomorrow.`);
        return;
    }

    if (!isWorkingHours()) {
        logger.warn(`Outside working hours (${cfg.get('working_hours.start')}h–${cfg.get('working_hours.end')}h). Exiting.`);
        return;
    }

    // Collect actionable leads
    const leads = [];
    for (let i = startRow; i <= sheet.actualRowCount; i++) {
        const row         = sheet.getRow(i);
        const company     = String(getCell(row, 'company') || '').trim();
        const stage       = String(getCell(row, 'stage') || '');
        const firstName   = String(getCell(row, 'first_name') || '').trim();
        const linkedinUrl = String(getCell(row, 'linkedin_url') || '').trim();
        const signal      = String(getCell(row, 'signal') || '').trim();
        const dateContact = getCell(row, 'date_contact');

        if (!company || !linkedinUrl || !linkedinUrl.includes('linkedin.com/in/')) continue;
        if (!firstName) { logger.info(`No contact name for ${company} — skip (run AxioMariuS first).`); continue; }

        const actionStage = getStage(stage, dateContact);
        if (!actionStage) continue;
        if (STAGE_ONLY && actionStage !== STAGE_ONLY) continue;
        if (alreadyProcessedToday(linkedinUrl)) continue;

        leads.push({ row, company, firstName, linkedinUrl, signal, actionStage, dateContact });
    }

    if (leads.length === 0) {
        logger.info('No leads to process today.');
        return;
    }

    const toProcess = leads.slice(0, quotaDay - todayDone);
    logger.info(`Processing ${toProcess.length} lead(s) (quota remaining: ${quotaDay - todayDone}).`);

    // Browser
    const browser = await puppeteer.launch({
        headless:        cfg.get('linkedin.headless', false),
        userDataDir:     path.resolve(process.cwd(), cfg.get('linkedin.session_dir', './chrome-session')),
        args:            ['--no-sandbox', '--disable-setuid-sandbox'],
        protocolTimeout: cfg.get('linkedin.protocol_timeout', 180000),
    });

    const page     = await browser.newPage();
    const delayMin = cfg.get('linkedin.delay_min', 30000);
    const delayMax = cfg.get('linkedin.delay_max', 90000);
    const stats    = { sent: 0, skipped: 0, errors: 0 };
    let   mustSave = false;

    const STATUS = {
        J0:  cfg.get('crm.status_j0',  'Invite sent'),
        J3:  cfg.get('crm.status_j3',  'Follow-up J+3'),
        J7:  cfg.get('crm.status_j7',  'Follow-up J+7'),
        J10: cfg.get('crm.status_j10', 'Closed J+10'),
    };

    try {
        for (const lead of toProcess) {
            const { row, company, firstName, linkedinUrl, signal, actionStage } = lead;

            logger.info(`\n── [${actionStage}] ${firstName} @ ${company} ──`);

            try {
                // Generate message
                const message = await polishMessage(firstName, company, signal, actionStage);
                logger.info(`Message (${message.length} chars): ${message.substring(0, 80)}...`);

                // Send
                let sent = false;
                if (actionStage === 'J0') {
                    sent = await sendConnectionRequest(page, linkedinUrl, message, DRY_RUN);
                } else {
                    sent = await sendDirectMessage(page, linkedinUrl, message, DRY_RUN);
                }

                if (sent) {
                    if (!DRY_RUN) {
                        setCell(row, 'stage',         STATUS[actionStage]);
                        setCell(row, 'date_contact',  actionStage === 'J0' ? new Date() : getCell(row, 'date_contact'));
                        setCell(row, 'next_contact',  null);
                        row.commit();
                        mustSave = true;
                    }
                    markAsProcessed(linkedinUrl);
                    stats.sent++;
                } else {
                    stats.skipped++;
                }

                await randomDelay(delayMin, delayMax);

            } catch (err) {
                logger.error(`Error processing ${company}: ${err.message}`);
                stats.errors++;
                if (!DRY_RUN) {
                    setCell(row, 'stage', cfg.get('crm.status_error', 'Error — retry'));
                    row.commit();
                    mustSave = true;
                }
            }
        }

    } finally {
        await browser.close();
        logger.info('Browser closed.');
    }

    if (mustSave && !DRY_RUN) {
        logger.info('Saving CRM...');
        await atomicWriteCRM(workbook, crmPath);
        logger.success('CRM saved.');
    }

    logger.endSession(stats.sent, stats.skipped, stats.errors);
    console.log('\n' + '═'.repeat(55));
    console.log('  Vantarius — Run Report');
    console.log('═'.repeat(55));
    console.log(`  Messages sent    : ${stats.sent}`);
    console.log(`  Skipped          : ${stats.skipped}`);
    console.log(`  Errors           : ${stats.errors}`);
    console.log(`  Total today      : ${getTodayCount()} / ${quotaDay}`);
    console.log('═'.repeat(55));
    console.log(`  Logs: ${logger.getLogPath()}`);
}

run().catch(err => {
    console.error('FATAL:', err);
    process.exit(1);
});
